<?php /** @var \Netresearch\OPS\Block\Info\Bancontact $this */ ?>
<?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?><br/>
<?php echo __('Payment ID: %1', $this->escapeHtml($this->getInfo()->getAdditionalInformation('paymentId'))) ?><br/>
<?php echo __('Status: %1', $this->getOPSHelper()->getStatusText($this->getInfo()->getAdditionalInformation('status'))) ?><br/>
<?php if ($this->getInfo()->hasAdditionalInformation('acceptance')): ?>
    <?php echo __('Acceptance: %1', $this->getInfo()->getAdditionalInformation('acceptance')) ?><br/>
<?php endif; ?>

<?php echo __('Device: %1', $this->getDeviceParameter()) ?><br/>
<?php echo __('Mobilemode: %1', $this->getMobileModeParameter()) ?><br/>

<?php $scoring = $this->getInfo()->getAdditionalInformation('scoring'); ?>
<?php $scoringCategory = $this->getInfo()->getAdditionalInformation('scoringCategory'); ?>

<?php
$scoringCssClass = '';
if (0 < strlen(trim($scoringCategory))):
    $scoringCssClass = 'scoring-' . $scoringCategory;
endif; ?>
<?php $scoringInformation = unserialize($this->getInfo()->getAdditionalInformation('additionalScoringData')); ?>
<?php if ($scoringInformation): ?>
    <table class="scoring <?php echo $this->escapeHtml($scoringCssClass); ?>">
        <tr>
            <th colspan="3" class="scoring scoring-<?php echo $this->escapeHtml($scoringCategory); ?>">
                <?php if (is_numeric($scoring) && 0 <= (int)$scoring): ?>
                    <?php echo __('Scoring Value: %1', $this->escapeHtml($scoring)) ?><br/>
                <?php endif; ?>
                <?php if (0 < strlen(trim($scoringCategory))): ?>
                    <?php echo __('Scoring Category: %1', $this->escapeHtml($scoringCategory)) ?>
                <?php endif; ?>
            </th>
        </tr>
        <?php if (true === is_array($scoringInformation)): ?>
            <?php foreach ($scoringInformation as $key => $value): ?>
                <tr>
                    <th><?php echo __($key); ?></th>
                    <td><?php echo $value; ?></td>
                    <td class="ops_scoring_description">
                        <?php $descriptionTranslationTemplate = 'SCORING_DESCRIPTION_' . $key; ?>
                        <?php $description = __($descriptionTranslationTemplate) ?>
                        <?php if ($description != $descriptionTranslationTemplate): ?>
                            <img src="<?php echo $this->getViewFileUrl('Netresearch_OPS::images/fam_help.gif') ?>" alt="?"/>
                            <div>
                                <?php echo $description ?>
                            </div>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        <?php endif; ?>
    </table>
<?php endif; ?>
<?php if ('O' == $scoringCategory): ?>
    <div class="notice-msg" style="padding: 9px 30px; margin-top: 3px">
        <?php echo __('This might be a fraud attempt. Please check details for more information.') ?>
    </div>
<?php endif; ?>
<?php if (!is_numeric($scoring) && 0 < strlen(trim($scoringCategory)) && 0 == sizeof($scoringInformation)): ?>
    <?php echo __('No scoring information available'); ?>
<?php endif; ?>
