<?php
/**
 * Copyright © 2016 MageWorx. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>
<?php /** @var $block \MageWorx\OptionInventory\Block\Adminhtml\Product\Edit\Tab\Options\Type\Select\Quantity\Option */ ?>
<td class="col-manage-stock">
    <input
        name="product[options][<%- data.id %>][values][<%- data.select_id %>][manage_stock]"
        type="hidden" value="0">
    <input id="product_option_<%- data.id %>_select_<%- data.select_id %>_manage_stock"
        <% if (data.manage_stock == 1) { %> checked="checked" <% } %>
        name="product[options][<%- data.id %>][values][<%- data.select_id %>][manage_stock]"
        class="product-option-manage_stock"
        type="checkbox" value="1" data-store-label="<%- data.manage_stock %>">
</td>