<?php
/**
 * Copyright © 2016 MageWorx. All rights reserved.
 * See LICENSE.txt for license details.
 */
/** @var \MageWorx\OptionFeatures\Block\Features $block */
?>
<script>
    require([
        'jquery',
        'optionFeatures',
        'uiRegistry'
    ], function ($, optionFeatures, registry) {
        var optionBase = registry.get('mageworxOptionBase');
        if (optionBase) {
            optionBase.addUpdater('optionFeatures', optionFeatures(<?php echo $block->getJsonData();?>));
        } else {
            var updaters = registry.get('mageworxOptionUpdaters');
            if (!updaters) {
                updaters = {};
            }
            updaters.optionFeatures = optionFeatures(<?php echo $block->getJsonData();?>);
            registry.set('mageworxOptionUpdaters', updaters);
        }
    });
</script>
