<?php
/**
 * Copyright © 2017 MageWorx. All rights reserved.
 * See LICENSE.txt for license details.
 */
use MageWorx\OptionFeatures\Model\Image;

/** @var $block \MageWorx\OptionFeatures\Block\Adminhtml\Gallery\Content */
$elementName = $block->getElement()->getName() . '[images]';
$formName = $block->getFormName();
?>
<form id="<?php echo $block->getHtmlId() ?>"
      class="gallery"
      data-mage-init='{"mageworxProductGallery":{"template":"#<?php echo $block->getHtmlId() ?>-template"}}'
      data-parent-component="<?php echo $block->escapeHtml($block->getData('config/parentComponent')) ?>"
      data-images="<?php echo $block->escapeHtml($block->getImagesJson()) ?>"
      data-types="<?php echo $block->escapeHtml(
          $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($block->getImageTypes())
      ) ?>"
>
    <?php if (!$block->getElement()->getReadonly()) { ?>
        <div class="image image-placeholder">
            <?php echo $block->getUploaderHtml(); ?>
            <div class="product-image-wrapper">
                <p class="image-placeholder-text">
                    <?php /* @escapeNotVerified */
                    echo __('Browse to find or drag image here'); ?>
                </p>
            </div>
        </div>
    <?php } ?>
    <?php foreach ($block->getImageTypes() as $typeData) {
        ?>
        <input name="<?php echo $block->escapeHtml($typeData['name']) ?>"
               data-form-part="<?php /* @escapeNotVerified */
               echo $formName ?>"
               class="image-<?php echo $block->escapeHtml($typeData['code']) ?>"
               type="hidden"
               value="<?php echo $block->escapeHtml($typeData['value']) ?>"/>
        <?php

    } ?>

    <script id="<?php echo $block->getHtmlId() ?>-template" type="text/x-magento-template">
        <div class="image item<% if (data.disabled == 1) { %> hidden-for-front<% } %>"
             data-role="image">
            <input type="hidden"
                   name="<?php /* @escapeNotVerified */
                   echo $elementName ?>[<%- data.file_id %>][position]"
                   value="<%- data.position %>"
                   class="position"/>
            <input type="hidden"
                   name="<?php /* @escapeNotVerified */
                   echo $elementName ?>[<%- data.file_id %>][file]"
                   value="<%- data.file %>"/>
            <input type="hidden"
                   name="<?php /* @escapeNotVerified */
                   echo $elementName ?>[<%- data.file_id %>][value_id]"
                   value="<%- data.value_id %>"/>
            <input type="hidden"
                   name="<?php /* @escapeNotVerified */
                   echo $elementName ?>[<%- data.file_id %>][label]"
                   value="<%- data.label %>"/>
            <input type="hidden"
                   name="<?php /* @escapeNotVerified */
                   echo $elementName ?>[<%- data.file_id %>][disabled]"
                   value="<%- data.disabled %>"/>
            <input type="hidden"
                   name="<?php /* @escapeNotVerified */
                   echo $elementName ?>[<%- data.file_id %>][media_type]"
                   value="image"/>
            <input type="hidden"
                   name="<?php /* @escapeNotVerified */
                   echo $elementName ?>[<%- data.file_id %>][removed]"
                   value=""
                   class="is-removed"/>
            <input type="hidden"
                   name="<?php /* @escapeNotVerified */
                   echo $elementName ?>[<%- data.file_id %>][custom_media_type]"
                   value="<%- data.custom_media_type %>"/>
            <input type="hidden"
                   name="<?php /* @escapeNotVerified */
                   echo $elementName ?>[<%- data.file_id %>][color]"
                   value="<%- data.color %>"/>

            <div class="product-image-wrapper">
                <img class="product-image"
                     data-role="image-element"
                     src="<%- data.url %>"
                     alt="<%- data.label %>"/>

                <div class="actions">
                    <button type="button"
                            class="action-remove"
                            data-role="delete-button"
                            title="<?php /* @escapeNotVerified */
                            echo __('Delete image') ?>">
                    <span>
                        <?php /* @escapeNotVerified */
                        echo __('Delete image') ?>
                    </span>
                    </button>
                    <div class="draggable-handle"></div>
                </div>
                <div class="image-fade"><span><?php /* @escapeNotVerified */
                        echo __('Hidden') ?></span></div>
            </div>


            <div class="item-description">
                <div class="item-title" data-role="img-title"><%- data.label %></div>
                <div class="item-size">
                    <span data-role="image-dimens"></span>, <span data-role="image-size"><%- data.sizeLabel %></span>
                </div>
            </div>

            <ul class="item-roles" data-role="roles-labels">
                <?php
                foreach ($block->getImageTypes() as $typeData) {
                    ?>
                    <li data-role-code="<?php /* @escapeNotVerified */
                    echo $block->escapeHtml(
                        $typeData['code']
                    ) ?>" class="item-role item-role-<?php /* @escapeNotVerified */
                    echo $block->escapeHtml(
                        $typeData['code']
                    ) ?>">
                        <?php /* @escapeNotVerified */
                        echo $block->escapeHtml($typeData['label']) ?>
                    </li>
                    <?php
                }
                ?>
            </ul>
        </div>
    </script>

    <script data-role="img-dialog-container-tmpl" type="text/x-magento-template">
        <div class="image-panel" data-role="dialog">
        </div>
    </script>

    <script data-role="img-dialog-tmpl" type="text/x-magento-template">
        <div class="image-panel-preview">
            <img src="<%- data.url %>" alt="<%- data.label %>"/>
        </div>
        <div class="image-panel-controls">
            <strong class="image-name"><%- data.label %></strong>

            <fieldset class="admin__fieldset fieldset-image-panel">

                <div class="admin__field field-image-description">
                    <label class="admin__field-label" for="image-description">
                        <span><?php /* @escapeNotVerified */
                            echo __('Text') ?></span>
                    </label>

                    <div class="admin__field-control">
                            <textarea data-role="image-description"
                                      rows="3"
                                      class="admin__control-textarea"
                                      name="<?php /* @escapeNotVerified */
                                      echo $elementName
                                      ?>[<%- data.file_id %>][label]"><%- data.label %></textarea>
                    </div>
                </div>

                <div class="admin__field field-image-role">
                    <label class="admin__field-label">
                        <span><?php /* @escapeNotVerified */
                            echo __('Role') ?></span>
                    </label>
                    <div class="admin__field-control">
                        <ul class="multiselect-alt">
                            <?php
                            foreach ($block->getMediaAttributes() as $attribute) :
                                ?>
                                <li class="item">
                                    <label>
                                        <input class="image-type"
                                               data-role="type-selector"
                                               data-form-part="<?php /* @escapeNotVerified */
                                               echo $formName ?>"
                                               type="checkbox"
                                               value="<?php /* @escapeNotVerified */
                                               echo $block->escapeHtml(
                                                   $attribute['code']

                                               ) ?>"
                                        />
                                        <?php /* @escapeNotVerified */
                                        echo $block->escapeHtml(
                                            $attribute['label']
                                        ) ?>
                                    </label>
                                </li>
                                <?php
                            endforeach;
                            ?>
                        </ul>
                    </div>
                </div>

                <div class="admin__field admin__field-inline field-image-size" data-role="size">
                    <label class="admin__field-label">
                        <span><?php /* @escapeNotVerified */
                            echo __('Image Size') ?></span>
                    </label>
                    <div class="admin__field-value" data-message="<?php /* @escapeNotVerified */
                    echo __('{size}') ?>"></div>
                </div>

                <div class="admin__field admin__field-inline field-image-resolution" data-role="resolution">
                    <label class="admin__field-label">
                        <span><?php /* @escapeNotVerified */
                            echo __('Image Resolution') ?></span>
                    </label>
                    <div class="admin__field-value" data-message="<?php /* @escapeNotVerified */
                    echo __('{width}^{height} px') ?>"></div>
                </div>

                <div class="admin__field field-image-hide">
                    <div class="admin__field-control">
                        <div class="admin__field admin__field-option">
                            <input type="checkbox"
                                   id="hide-from-option-gallery"
                                   data-role="visibility-trigger"
                                   data-form-part="<?php echo $formName; ?>"
                                   value="1"
                                   class="admin__control-checkbox"
                                   name="<?php echo $elementName ?>[<%- data.file_id %>][<?php echo Image::COLUMN_HIDE_IN_GALLERY; ?>]"
                            <% if (data.<?php echo Image::COLUMN_HIDE_IN_GALLERY; ?> == 1) { %>checked="checked"<% } %>
                            />

                            <label for="hide-from-option-gallery" class="admin__field-label">
                                <?php echo __('Hide from Option Gallery'); ?>
                            </label>
                        </div>
                    </div>
                </div>
            </fieldset>
        </div>
    </script>
</form>
<script>
    jQuery('body').trigger('contentUpdated');
</script>
