<?php $link = $block->getEditLink();?>
<?php if(is_array($link)) : ?>
<?php
$type = $link['type'];
$url = $link['url'];
switch ($type) {
	case 'product':
		$title = __('Edit Product');
		break;
	case 'category':
		$title = __('Edit Category');
		break;
	case 'customer':
		$title = __('Edit Customer');
		break;
	case 'cms':
		$title = __('Edit Cms Page');
		break;
	case 'staticblock':
		$title = __('Edit Static Block');
		break;
	default:
		$title = __('Edit Link');
		break;
}
?>
<a class="click-me bss-adminpreview-backend" target="_blank" href="<?php echo $url ?>"><?php echo $title ?></a>
<style>
.bss-adminpreview-backend {background-color: #f7531b;color: #fff !important;display: inline-block;font-weight: bold;padding: 3px 8px!important;position: relative;z-index: 999;}
</style>
<?php endif ?>