<?php
/**
 * Copyright © 2016 MageWorx. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>
<?php /** @var $block \MageWorx\OptionInventory\Block\Adminhtml\Product\Edit\Tab\Options\Type\Select\Quantity\Option */ ?>
<td class="col-qty">
    <input id="product_option_<%- data.id %>_select_<%- data.select_id %>_qty"
        name="product[options][<%- data.id %>][values][<%- data.select_id %>][qty]"
        class="input-text validate-number product-option-qty"
        type="text" value="<%- data.qty %>" data-store-label="<%- data.qty %>">
</td>