<?php /** @var \Amasty\Checkout\Block\Sales\Order\Info\Delivery $block */?>
<?php if ($fields = $block->getDeliveryDateFields()): ?>
    <div class="block ">
        <div class="block-title"><strong><?= __('Delivery Information') ?></strong></div>
        <div class="block-content">
            <div class="box">
                <?php foreach ($fields as $field): ?>
                    <div class="box-content">
                        <p><?= __($field['label']); ?>: <?= $field['value']; ?></p>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
<?php endif ?>
