<?php
/**
 * @category   OPS
 * @package    Netresearch_OPS
 * @author     Thomas Birke <thomas.birke@netresearch.de>
 * @author     Michael Lühr <michael.luehr@netresearch.de>
 * @copyright  Copyright (c) 2012 Netresearch GmbH & Co. KG
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * \Netresearch\OPS\Block\Form\Alias
 *
 * @author     Thomas Birke <thomas.birke@netresearch.de>
 * @author     Michael Lühr <michael.luehr@netresearch.de>
 * @copyright  Copyright (c) 2012 Netresearch GmbH & Co. KG
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/** @var \Netresearch\OPS\Block\Form\Alias $this */
?>
<?php $code = $this->getMethodCode() ?>

<ul class="form-list ops-form-list" id="payment_form_<?php echo $code ?>" style="display:none;">
    <li>
        <?php $inputType = (1 < count($this->getAvailableAliases())) ? 'radio' : 'hidden' ?>
        <?php foreach ($this->getAvailableAliases() as $offset=>$alias): ?>
            <div class="ops_alias_option_details">
                <input type="<?php echo $inputType ?>" name="payment[ops_alias]" value="<?php echo $alias->getAlias(); ?>" id="ops_alias_option_<?php echo $offset ?>">
                <label for="ops_alias_option_<?php echo $offset ?>">
                    <?php echo __('Credit Card') ?>
                    <?php echo $alias->getPseudoAccountOrCCNo(); ?>
                    (<?php echo __($alias->getBrand()); ?>)<br />
                    <?php echo __('expires: %1', $alias->getExpirationDate()) ?>
                </label>
            </div>

        </select>
        <?php endforeach; ?>
    </li>
</ul>
