<?php
/** @var $this \Netresearch\OPS\Block\Form\Ideal */
$issuers = $this->getIssuers();
?>
<ul class="form-list ops-form-list" id="payment_form_ops_iDeal" style="display:none;">
    <li>
        <select name="payment[iDeal_issuer_id]" id="ops_iDeal_issuer_id" class="required-entry">
            <option value=""><?php echo __('--Please Select--'); ?></option>
            <?php foreach ($issuers as $key => $value): ?>
                <option value=<?php echo $this->escapeHtml($key) ?>>
                    <?php echo $this->escapeHtml($value) ?>
                </option>
            <?php endforeach; ?>
        </select>
    </li>
    <p><?php echo $this->getRedirectMessage(); ?></p>
</ul>
