<?php
 
/**
 * Copyright © 2017 x-mage2(Yosto). All rights reserved.
 * See README.md for details.
 */
 
use Magento\Framework\App\Action\Action;
use Magento\ConfigurableProduct\Model\Product\Type\Configurable;

// @codingStandardsIgnoreFile
?>
<?php $iterator = 1; ?>
<?php foreach ($items as $_item): ?>
    <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="product-item item">' : '</li><li class="product-item item">' ?>
    <?php if($enableCustomCss == 1): ?>
        <i class="fa fa-ellipsis-v" aria-hidden="true"></i>
    <?php endif;?>
    <div class="product-item-info">
        <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product-item-photo">
            <?php echo $block->getImage($_item, $image)->toHtml(); ?>
        </a>
        <div class="product details product-item-details">
            <strong class="product-item-name">
                <a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                   href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>"
                   class="product-item-link">
                    <?php echo $block->escapeHtml($_item->getName()) ?>
                </a>
            </strong>
            <?php if ($templateType): ?>
                <?php echo $block->getReviewsSummaryHtml($_item, $templateType, true) ?>
            <?php endif; ?>
            <?php
            echo $block->getProductPriceHtml($_item, $type);
            ?>
            <?php if($showSwatches) : ?>
                <?php echo $block->getProductDetailsHtml($_item); ?>
            <?php endif;?>
            <?php if ($showWishlist || $showCompare || $showCart): ?>
                <div class="product-item-actions">
                    <?php if ($showCart): ?>
                        <div class="actions-primary">
                            <?php if ($_item->isSaleable()): ?>
                                <?php $postParams = $block->getAddToCartPostParams($_item); ?>
                                <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                    <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                    <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                    <?php echo $block->getBlockHtml('formkey')?>
                                    <button type="submit"
                                            title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                            class="action tocart primary">
                                        <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                    </button>
                                </form>
                            <?php else: ?>
                                <?php if ($_item->getIsSalable()): ?>
                                    <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                <?php else: ?>
                                    <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                <?php endif; ?>
                            <?php endif; ?>
                        </div>
                    <?php endif; ?>
                    <?php if ($showWishlist || $showCompare): ?>
                        <div class="actions-secondary" data-role="add-to-links">
                            <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                <a href="#"
                                   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'
                                   class="action towishlist" data-action="add-to-wishlist"
                                   title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
                                    <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                </a>
                            <?php endif; ?>
                            <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
                                <a href="#" class="action tocompare"
                                   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_item);?>'
                                   title="<?php /* @escapeNotVerified */ echo __('Add to Compare') ?>">
                                    <span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
                                </a>
                            <?php endif; ?>
                        </div>
                    <?php endif; ?>
                </div>
            <?php endif; ?>
        </div>
    </div>
    <?php echo($iterator == count($items)+1) ? '</li>' : '' ?>
<?php endforeach ?>

