<?php /** @var $block \Amasty\Checkout\Block\Onepage\Success\Details */ ?>
<div class="account">
    <div class="column main">
        <div class="block block-order-details">
            <div class="block-title">
                <strong><?= __('Order details:') ?></strong>
            </div>
            <div class="order-date">
                <?= __('Order Date:') ?> <?= $block->formatDate($block->getOrder()->getCreatedAt(), \IntlDateFormatter::LONG) ?>
                <?= $block->getChildHtml('delivery') ?>
                <span class="delivery-date"><?= $block->getDeliveryInfo() ?></span>
            </div>
        </div>

        <?= $block->getChildHtml('info') ?>
        <?= $block->getChildHtml('comments') ?>
        <?= $block->getChildHtml('order_view') ?>
    </div>
</div>
