<?php
/**
 * Copyright © 2016 MageWorx. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "mageworx_select_js": {
                    "component": "MageWorx_OptionDependency/js/select"
                }
            }
        }
    }
}
</script>
<script>
    require([
        'jquery',
        'optionDependency',
        'uiRegistry'
    ], function ($, optionDependency, registry) {
        var optionBase = registry.get('mageworxOptionBase');
        if (optionBase) {
            optionBase.addUpdater('optionDependency', optionDependency(<?php echo $block->getJsonData();?>));
        } else {
            var updaters = registry.get('mageworxOptionUpdaters');
            if (!updaters) {
                updaters = {};
            }
            updaters.optionDependency = optionDependency(<?php echo $block->getJsonData();?>);
            registry.set('mageworxOptionUpdaters', updaters);
        }
    });
</script>