<?php
/**
 * Copyright © 2016 x-mage2(Yosto). All rights reserved.
 * See README.md for details.
 */
namespace Yosto\Slider\Block\Adminhtml\Image;

use Magento\Framework\View\Element\Template;
use Yosto\Slider\Model\ImageFactory;

/**
 * Class Preview
 * @package Yosto\Slider\Block\Adminhtml\Image
 */
class Preview extends Template
{
    /**
     * @var ImageFactory
     */
    protected $_imageFactory;

    /**
     * @param Template\Context $context
     * @param ImageFactory $imageFactory
     * @param array $data
     */
    public function __construct(
        Template\Context $context,
        ImageFactory $imageFactory,
        array $data = []
    ) {
        $this->_imageFactory = $imageFactory;
        parent::__construct($context, $data); // TODO: Change the autogenerated stub
    }
}