<?php
/**
 * Copyright © 2017 x-mage2(Yosto). All rights reserved.
 * See README.md for details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Template for displaying products list widget
 *
 * @var $block \Magento\CatalogWidget\Block\Product\ProductsList
 */
$currentClass = "block-grid-products";
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())):?>
    <?php include($this->getTemplateFile('Yosto_ProductSlider::product/widget/parts/general-config.phtml')); ?>
    <div class="block widget yosto-custom-widget <?php echo $modalThemeClass ?> block-grid-products <?php /* @escapeNotVerified */ echo $mode; ?>">
        <?php if ($title):?>
            <div class="yosto-product-slider-heading">
                <h2><span><?php echo  $title; ?></span></h2>
            </div>
        <?php endif ?>
        <div class="block-content">
            <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
            <div class="products-<?php /* @escapeNotVerified */ echo $mode; ?> <?php /* @escapeNotVerified */ echo $mode; ?>">
                <ol class="product-items <?php /* @escapeNotVerified */ echo $type; ?>">
                    <?php include($this->getTemplateFile('Yosto_ProductSlider::product/widget/parts/slider-item.phtml')); ?>
                </ol>
            </div>
            <?php echo $block->getPagerHtml() ?>
        </div>
    </div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
    <?php include($this->getTemplateFile('Yosto_ProductSlider::product/widget/parts/secondary-actions-js.phtml')); ?>
<?php endif;?>
