<?php
$urlInterface = \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Framework\UrlInterface');
$url = $urlInterface->getCurrentUrl();
$selectedDay = $block->getRequest()->getParam('day');
?>
    <div class="field overview required" style="float: right">
        <button type="button" id="today_revenue" title="Today" name="today_revenue" class="action-default">
            <?php echo __('Today') ?>
        </button>
     <span class="field-row">
         <input class="input-text no-changes required-entry admin__control-text"
                type="text"
                id="date_from"
                value="<?php echo $selectedDay!=null?date('Y-m-d', strtotime($selectedDay)):'';?>"
                name="from"
             />
           <span id="date_from_advice"></span>
       </span>
        <button type="button" id="revenue_day" title="Refresh" name="revenue_day" class="action-default primary">
            <?php echo __('Refresh') ?>
        </button>
    </div>
<script>
    require([
        "jquery",
        "mage/calendar"
    ], function ($) {
        $("#date_from").calendar({
            buttonText: "<?php echo __('Select Date') ?>",
            dateFormat: "yyyy-mm-dd"
        });
        $("#revenue_day").click(function () {
            var currentUrl = '<?php echo $url ?>';
            currentUrl = currentUrl.replace(/day\/\d+\//,'');
            var newLocation = currentUrl+"day/"+ $('#date_from').val().replace(/-/g,'')+"/"
            setLocation(newLocation);
        });
        $("#today_revenue").click(function (){
            var currentUrl = '<?php echo $url ?>';
            currentUrl = currentUrl.replace(/day\/\d+\//,'');
            setLocation(currentUrl);
        });
    });
</script>