<?php
/**
 * Copyright © 2016 x-mage2(Yosto). All rights reserved.
 * See README.md for details.
 */
namespace Yosto\Slider\Block\Adminhtml\Image\Edit\Tab;

use Magento\Backend\Block\Widget\Form\Generic;
use Magento\Backend\Block\Widget\Tab\TabInterface;
use Magento\Backend\Block\Template\Context;
use Magento\Framework\Data\FormFactory;
use Magento\Framework\Registry;
use Yosto\Slider\Model\Image\ContentPosition;

/**
 * Class DefaultSetting
 * @package Yosto\Slider\Block\Adminhtml\Image\Edit\Tab
 */
class DefaultSetting extends Generic implements TabInterface
{
    /**
     * @var ContentPosition
     */
    protected $_contentPosition;

    /**
     * @param Context $context
     * @param Registry $registry
     * @param FormFactory $formFactory
     * @param ContentPosition $contentPosition
     * @param array $data
     */
    public function __construct(
        Context $context,
        Registry $registry,
        FormFactory $formFactory,

        array $data = []
    ) {
        parent::__construct($context, $registry, $formFactory, $data);
    }

    /**
     * @return $this
     * @throws \Magento\Framework\Exception\LocalizedException
     */
    protected function _prepareForm()
    {
        $model=$this->_coreRegistry->registry('slider_image');
        $form=$this->_formFactory->create();
        $form->setHtmlIdPrefix('image_');
        $form->setFieldNameSuffix('image');
        $fieldset=$form->addFieldset(
            'default_setting_image',
            ['legend'=>__('Default Setting')]
        );
        $fieldset->addField(
            'content_width',
            'text',
            [
                'name'=>'content_width',
                'label'=>__('Content width'),
                'note' => 'Default value is 90%'
            ]
        );
        $fieldset->addField(
            'title_font_size',
            'text',
            [
                'name'=>'title_font_size',
                'label'=>__('Title font size'),
                'note'=>__('Font-size will be fixed on all devices if you set a value.')
            ]
        );
        $fieldset->addField(
            'title_color',
            'text',
            [
                'name' => 'title_color',
                'label' => __('Title Color'),
                'class' =>  'jscolor {hash:true,refine:false}',
                'note' => 'Default color is white.'
            ]
        );

        $fieldset->addField(
            'subtitle_color',
            'text',
            [
                'name' => 'subtitle_color',
                'label' => __('Subtitle Color'),
                'class' =>  'jscolor {hash:true,refine:false}',
                'note' => 'Default color is black.'
            ]
        );
        $fieldset->addField(
            'subtitle_font_size',
            'text',
            [
                'name'=>'subtitle_font_size',
                'label'=>__('Subtitle font size'),
                'note'=>__('Font-size will be fixed on all devices if you set a value.')
            ]
        );
        $fieldset->addField(
            'button_title_color',
            'text',
            [
                'name' => 'button_title_color',
                'label' => __('Button Title Color'),
                'class' =>  'jscolor {hash:true,refine:false}'
            ]
        );
        $fieldset->addField(
            'button_font_size',
            'text',
            [
                'name'=>'button_font_size',
                'label'=>__('Button font size'),
                'note'=>__('Font-size will be fixed on all devices if you set a value.')
            ]
        );

        $fieldset->addField(
            'button_backgroud_color',
            'text',
            [
                'name' => 'button_backgroud_color',
                'label' => __('Button Background Color'),
                'class' =>  'jscolor {hash:true,refine:false}',
                'note' => 'Default color is orange.'
            ]
        );

        $data = $model->getData();
        if (!$model->getImageId()) {
            $data['button_backgroud_color'] = '#f50';
            $data['button_title_color'] = '#ffffff';
            $data['subtitle_color'] = '#000000';
            $data['title_color'] = '#ffffff';
            $data['content_width'] = '90';

        }
        $form->setValues($data);
        $this->setForm($form);
        return parent::_prepareForm(); // TODO: Change the autogenerated stub
    }

    /**
     * @return \Magento\Framework\Phrase
     */
    public function getTabLabel()
    {
        return __('Default Setting');
    }

    /**
     * @return \Magento\Framework\Phrase
     */

    public function getTabTitle()
    {
        return __('Default Setting');
    }

    /**
     * @return bool
     */
    public function canShowTab()
    {
        return true;
    }

    /**
     * @return bool
     */
    public function isHidden()
    {
        return false;
    }

}