<?php
/**
 * Copyright © 2016 x-mage2(Yosto). All rights reserved.
 * See README.md for details.
 */
namespace Yosto\Slider\Block\Adminhtml\Image\Edit\Tab;
use Magento\Backend\Block\Template\Context;
use Magento\Backend\Block\Widget\Form\Generic;
use Magento\Backend\Block\Widget\Tab\TabInterface;
use Magento\Framework\Data\FormFactory;
use Magento\Framework\Registry;
use Yosto\Slider\Model\Image\ContentPosition;
use Yosto\Slider\Model\Image\Effect as EffectOptions;

/**
 * Class Effect
 * @package Yosto\Slider\Block\Adminhtml\Image\Edit\Tab
 */
class Effect extends Generic implements TabInterface
{
    /**
     * @var ContentPosition
     */
    protected $_contentPosition;

    /**
     * @var EffectOptions
     */
    protected $_effect;


    /**
     * @param Context $context
     * @param Registry $registry
     * @param FormFactory $formFactory
     * @param ContentPosition $contentPosition
     * @param EffectOptions $effect
     * @param array $data
     */
    public function __construct(
        Context $context,
        Registry $registry,
        FormFactory $formFactory,
        ContentPosition $contentPosition,
        EffectOptions $effect,
        array $data = []
    ) {
        $this->_contentPosition = $contentPosition;
        $this->_effect = $effect;
        parent::__construct($context, $registry, $formFactory, $data);
    }

    /**
     * @return $this
     * @throws \Magento\Framework\Exception\LocalizedException
     */
    protected function _prepareForm()
    {
        $model = $this->_coreRegistry->registry('slider_image');
        $form = $this->_formFactory->create();
        $form->setHtmlIdPrefix('image_');
        $form->setFieldNameSuffix('image');
        $fieldset = $form->addFieldset(
            'effect_fieldset',
            ['legend' => __('Effect')]
        );

        $fieldset->addField(
          'title_effect',
            'select',
            [
                'name' => 'title_effect',
                'label' => __('Effect for Title'),
                'values' => $this->_effect->toOptionArray()
            ]
        );

        $fieldset->addField(
            'subtitle_effect',
            'select',
            [
                'name' => 'subtitle_effect',
                'label' => __('Effect for Subtitle'),
                'values' => $this->_effect->toOptionArray()
            ]
        );

        $fieldset->addField(
            'button_effect',
            'select',
            [
                'name' => 'button_effect',
                'label' => __('Effect for Button'),
                'values' => $this->_effect->toOptionArray()
            ]
        );
        $data = $model->getData();
        $form->setValues($data);
        $this->setForm($form);
        return parent::_prepareForm(); // TODO: Change the autogenerated stub
    }

    /**
     * @return \Magento\Framework\Phrase
     */
    public function getTabLabel()
    {
        return __('Effect');
    }

    /**
     * @return \Magento\Framework\Phrase
     */
    public function getTabTitle()
    {
        return __('Effect');
    }

    /**
     * @return bool
     */
    public function canShowTab()
    {
        return true;
    }

    /**
     * @return bool
     */
    public function isHidden()
    {
        return false;
    }

}