<?php
/**
 * \Netresearch\OPS\Block\Form\OpsId
 * 
 * @category  design
 * @package   OPS
 * @copyright 2012 Netresearch App Factory AG <http://www.netresearch.de>
 * @author    Thomas Birke <thomas.birke@netresearch.de> 
 * @license   OSL 3.0
 */
?>

<fieldset class="admin__fieldset payment-method" id="payment_form_<?php /* @noEscape */ echo $this->getMethodCode(); ?>"
          style="display:none">
    <div class="field-payId admin__field _required">
        <label class="admin__field-label" for="ops_payId">
            <span><?php echo __('Ingenico ePayments Transaction ID'); ?><em class="required">*</em></span>
        </label>
        <div class="admin__field-control">
            <input type="text" id="ops_payId" name="payment[ops_pay_id]" title="<?php echo __("Ingenico ePayments payment id") ?>" class="required-entry input-text" value="<?php echo $this->getInfoData('OpsPayId'); ?>"/>
        </div>
    </div>
</fieldset>
