<?php
/**
 * Copyright © 2016 x-mage2(Yosto). All rights reserved.
 * See README.md for details.
 */
?>

<script>
    require([
        'jquery',
        'Magento_Ui/js/modal/alert'
    ], function ($, alert) {
        window.smsAppTest = function(){

            $.ajax({
                url: '<?php echo $block->getAdminUrl() ?>',
                type: 'post',
                dataType: 'html',
                data: {
                    form_key: FORM_KEY,
                    sid: $('#twiliosmsnotification_twilioconfig_account_sid').val(),
                    token:$('#twiliosmsnotification_twilioconfig_account_token').val(),
                    your_phone:$('#twiliosmsnotification_testsms_your_phone').val(),
                    phone:$('#twiliosmsnotification_twilioconfig_phone').val(),
                },
                showLoader: true
            }).done(function(data) {
                alert({
                    title:'Result',
                    content:data
                });
            });
        }
    });
</script>

<?php echo $block->getButtonHtml() ?>
