<?php
/**
 * Copyright © 2016 x-mage2(Yosto). All rights reserved.
 * See README.md for details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $this \Yosto\AdvancedReport\Block\Adminhtml\Report\Customer\Geolocation */ ?>
<?php
    $collection = $block->getCollection();
?>

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<div id="regions_div" style="width: 100%;"></div>
<script type="text/javascript">
    google.charts.load('current', {'packages':['geochart']});
    google.charts.setOnLoadCallback(drawRegionsMap);

    function drawRegionsMap() {
        var data = google.visualization.arrayToDataTable([
            ['Country', 'Total'],
            <?php foreach($collection as $row): ?>
            ['<?php /* @escapeNotVerified */ echo $row['country']; ?>', <?php /* @escapeNotVerified */ echo $row['orders_sum_amount'] ?>],
            <?php endforeach; ?>
        ]);

        var options = {};
        options['dataMode'] = 'regions';
        var chart = new google.visualization.GeoChart(document.getElementById('regions_div'));

        chart.draw(data, options);
    };
</script>
