<?php
/**
 * Copyright © 2017 MageWorx. All rights reserved.
 * See LICENSE.txt for license details.
 */
/** @var \MageWorx\OptionSwatches\Block\Swatches $block */
?>
<script>
    require([
        'jquery',
        'optionSwatches',
        'uiRegistry'
    ], function ($, optionSwatches, registry) {
        var optionBase = registry.get('mageworxOptionBase');
        if (optionBase) {
            optionBase.addUpdater('optionSwatches', optionSwatches());
        } else {
            var updaters = registry.get('mageworxOptionUpdaters');
            if (!updaters) {
                updaters = {};
            }
            updaters.optionSwatches = optionSwatches();
            registry.set('mageworxOptionUpdaters', updaters);
        }
    });
</script>
